version: "3.7"
services:
  loki:
    image: grafana/loki:2.6.1
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100" # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  grafana:
    image: grafana/grafana:9.3.0
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  # # otel-collector:
  # #   image: otel/opentelemetry-collector-dev:latest
  # #   command: ["--config=/etc/otel-collector-config.yaml"]
  # #   volumes:
  # #     - ./otel-config.yaml:/etc/otel-collector-config.yaml
  # #   ports:
  # #     - "1888:1888"   # pprof extension
  # #     - "8888:8888"   # Prometheus metrics exposed by the collector
  # #     - "8889:8889"   # Prometheus exporter metrics
  # #     - "13133:13133" # health_check extension
  # #     - "4317"        # OTLP gRPC receiver
  # #     - "55670:55679" # zpages extension
  # #   depends_on:
  # #     - tempo
  # #     - prometheus

  # ecommerce:
  #   build: ../e-commerce
  #   ports:
  #     - 8080:8080
  #     - 9464:9464 # For Prometheus

  # car:
  #   build: ../car
  #   ports:
  #     - 3001:3001

  # house:
  #   build: ../house
  #   ports:
  #     - 3002:3002
