apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-deployment
  labels:
    app: car
spec:
  replicas: 3
  selector:
    matchLabels:
      app: car
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: car
    spec:
      containers:
        - name: car
          image: ghassenda/projetdevops-car
          ports:
            - containerPort: 3001
