apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    prometheus/scrape: "true"
    prometheus/path: "/metrics"
    prometheus/port: "9090"
  namespace: monitoring
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30000