apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    prometheus/scrape: "true"
    prometheus/path: "/metrics"
    prometheus/port: "9464"
spec:
  selector:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}

  ports:
    - protocol: TCP
      port: {{ .Values.http.port }}
      name: "app"
    - name: "prometheus"
      port: 9464
      targetPort: 9464
