apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- range $key, $val := .Values.labels }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    spec:
      containers:
        - name: { { .Values.container.name } }
          image: { { .Values.image.name } }:{{ .Values.image.tag }}
          imagePullPolicy: "Always"
          ports:
            - containerPort: { { .Values.http.port } }
            - containerPort: 9464
