receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug

  otlp:
    endpoint: tempo:4317
    insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
